// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQjFnpXA3B06fTiiXHrwIhOpEb6wsAA4',
    appId: '1:871079602289:web:0b8760d1f9ac73516a93d0',
    messagingSenderId: '871079602289',
    projectId: 'learning-auth-6089f',
    authDomain: 'learning-auth-6089f.firebaseapp.com',
    storageBucket: 'learning-auth-6089f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJImO3kD02xHKfPW8mhBlnDRx_xuaFFw',
    appId: '1:871079602289:android:598b498771e545426a93d0',
    messagingSenderId: '871079602289',
    projectId: 'learning-auth-6089f',
    storageBucket: 'learning-auth-6089f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPu9JGt4O5Wjs4wqT0w5cTocyu5jnczU',
    appId: '1:871079602289:ios:187448eb2cc6c4886a93d0',
    messagingSenderId: '871079602289',
    projectId: 'learning-auth-6089f',
    storageBucket: 'learning-auth-6089f.appspot.com',
    iosBundleId: 'com.example.learningAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtPu9JGt4O5Wjs4wqT0w5cTocyu5jnczU',
    appId: '1:871079602289:ios:187448eb2cc6c4886a93d0',
    messagingSenderId: '871079602289',
    projectId: 'learning-auth-6089f',
    storageBucket: 'learning-auth-6089f.appspot.com',
    iosBundleId: 'com.example.learningAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyQjFnpXA3B06fTiiXHrwIhOpEb6wsAA4',
    appId: '1:871079602289:web:e7b543af873221c06a93d0',
    messagingSenderId: '871079602289',
    projectId: 'learning-auth-6089f',
    authDomain: 'learning-auth-6089f.firebaseapp.com',
    storageBucket: 'learning-auth-6089f.appspot.com',
  );
}
